services:
  postgres:
    image: postgres:16
    container_name: mini_saas_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chluk566ov1
      POSTGRES_DB: mini_saas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: